### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by jakehunter** [generoi/wp-gutenberg-templates#2]
Fatal error: Trait 'GeneroWP\Common\Singleton' not found in .../wp-content/plugins/wp-gutenberg-templates-master/plugin.php on line 32

**Comment by oxyc** [comment]
this plugin should be installed with composer. Or you can run `composer install` in the plugin directory.

**Comment by jakehunter** [comment]
Thank you 👍
